{/* AI Summary Modal Overlay */}
{aiSummary && (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
    <div className="relative w-full max-w-4xl max-h-[85vh] overflow-y-auto rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 shadow-2xl p-8">
      
      {/* Close Button */}
      <button 
        onClick={() => setAiSummary(null)} 
        className="absolute top-4 right-4 p-2 text-slate-400 hover:text-red-500 transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
      </button>

      {/* Header */}
      <div className="mb-6 flex items-center gap-3 border-b border-slate-100 dark:border-slate-800 pb-4">
        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/><path d="M5 3v4"/><path d="M9 3v4"/><path d="M3 5h4"/><path d="M3 9h4"/></svg>
        </div>
        <div>
           <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Executive Summary</h2>
           <p className="text-sm text-slate-500">Generated by AI • Includes PR Sources</p>
        </div>
      </div>

      {/* The AI Content - Rendered as HTML */}
      <div 
        className="prose prose-sm md:prose-base dark:prose-invert max-w-none 
                   prose-a:text-sky-600 dark:prose-a:text-sky-400 prose-a:no-underline hover:prose-a:underline
                   prose-ul:space-y-2 prose-li:marker:text-slate-300"
        dangerouslySetInnerHTML={{ __html: aiSummary }} 
      />
    </div>
  </div>
)}

{/* ... inside your Header/Button area ... */}
<button
  onClick={generateAiSummary}
  disabled={aiLoading}
  className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-purple-600 to-indigo-600 px-4 py-2 text-xs font-bold text-white shadow-lg shadow-purple-500/25 transition-all hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
>
  {aiLoading ? (
    <>Processing...</> 
  ) : (
    <>
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
      Generate AI Summary
    </>
  )}
</button>
